# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

getall_reseaux:
    path: /getAllNetworks
    defaults: { _controller: App\Controller\ReseauxController::getAllReseaux }

getall_mesures:
    path: /getAllMeasures
    defaults: { _controller: App\Controller\MesuresController::getAllMesures }

create_reseaux:
    path: /createNetwork
    defaults: { _controller: App\Controller\ReseauxController::createReseaux }

create_mesures:
    path: /createMeasure
    defaults: { _controller: App\Controller\MesuresController::createMesures }

get_map: 
    path: /getMap
    defaults: { _controller: App\Controller\MapController::getMap }